=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Simulacro Examen/Factura2/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="datos_emisor" type="TipoDatos"/>
                
                <xs:element name="datos_cliente" type="TipoDatos"/>

                <xs:element name="detalle_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="linea" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="codigo" type="xs:string"/>
                                        <xs:element name="tipo" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="cantidad" type="xs:integer"/>
                                        
                                        <xs:element name="oferta">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="SI"/>
                                                    <xs:enumeration value="NO"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        
                                        <xs:element name="pvp" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="importe_total" type="xs:decimal"/>

            </xs:sequence>
            
            <xs:attribute name="numero" type="xs:integer" use="required"/>
            <xs:attribute name="fecha" type="xs:date" use="required"/>
            
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TipoDatos">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="cif" type="xs:string"/>
            <xs:element name="telefono" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Simulacro Examen/Factura2/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="factura.xsl"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura.xsd" numero="27" fecha="2013-12-18">
    
    <datos_emisor>
        <nombre>Librería Pérez</nombre>
        <cif>44555666B</cif>
        <telefono>777888999</telefono>
    </datos_emisor>

    <datos_cliente>
        <nombre>Biblioteca Txantrea</nombre>
        <cif>33111222A</cif>
        <telefono>333999444</telefono>
    </datos_cliente>

    <detalle_factura>
        <linea>
            <codigo>AW7</codigo>
            <tipo>Libro</tipo>
            <descripcion>Analítica Web 2.0</descripcion>
            <cantidad>1</cantidad>
            <oferta>SI</oferta>
            <pvp>25.12</pvp>
        </linea>
        <linea>
            <codigo>CP5</codigo>
            <tipo>DVD</tipo>
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <oferta>NO</oferta>
            <pvp>30.5</pvp>
        </linea>
    </detalle_factura>

    <importe_total>86.12</importe_total>

</factura>
