=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 7 DTD - XML/receta.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT receta (nombre, ingredientes, instrucciones)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT instrucciones (#PCDATA)>

<!ELEMENT ingredientes (ingrediente+)>

<!ELEMENT ingrediente (#PCDATA)>

<!ATTLIST receta 
    raciones CDATA #REQUIRED
    dificultad (baja|media|alta) "media">

<!ATTLIST ingrediente 
    cantidad CDATA #IMPLIED
    unidad CDATA #IMPLIED>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 7 DTD - XML/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta SYSTEM "receta.dtd">

<receta raciones="4">
    <nombre>Tortilla de Patatas Española</nombre>
    
    <ingredientes>
        <ingrediente cantidad="4" unidad="unidades">Huevos L</ingrediente>
        
        <ingrediente cantidad="1" unidad="kg">Patatas gallegas</ingrediente>
        
        <ingrediente>Aceite de oliva virgen extra</ingrediente>
        <ingrediente>Sal</ingrediente>
    </ingredientes>
    
    <instrucciones>
        Pelar y cortar las patatas. Freírlas en abundante aceite. 
        Batir los huevos. Mezclar todo y cuajar en la sartén al gusto.
    </instrucciones>
</receta>
