=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 9 XSD - XML/pelicula.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pelicula">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="director" type="xs:string"/>
                <xs:element name="sinopsis" type="xs:string"/>
                
                <xs:element name="actor" type="xs:string" maxOccurs="unbounded"/>
                
                <xs:element name="anio" type="xs:integer" minOccurs="0"/>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 9 XSD - XML/pelicula.xml
<?xml version="1.0" encoding="UTF-8"?>
<pelicula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pelicula.xsd">
    
    <titulo>El Señor de los Anillos: La Comunidad del Anillo</titulo>
    <director>Peter Jackson</director>
    <sinopsis>Un hobbit hereda un anillo que puede destruir el mundo.</sinopsis>
    
    <actor>Elijah Wood</actor>
    <actor>Ian McKellen</actor>
    <actor>Viggo Mortensen</actor>

    <anio>2001</anio>

</pelicula>
