=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Simulacro Examen/Factura3/personal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="registro_personal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datos_generales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empresa" type="xs:string"/>
                            <xs:element name="trabajadores" type="xs:integer"/>
                            <xs:element name="multinacional" type="TipoSiNo"/>
                            <xs:element name="moneda" type="xs:string"/>
                            <xs:element name="sector" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre_dept" type="xs:string"/>
                                        <xs:element name="empleado" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="rol" type="xs:string"/>
                                                    <xs:element name="baja" type="TipoSiNo"/>
                                                    <xs:element name="salario" type="xs:decimal"/>
                                                    <xs:element name="usuario" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="clave" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="fecha" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="TipoSiNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SI"/>
            <xs:enumeration value="NO"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Simulacro Examen/Factura3/personal.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="personal.xsl"?>
<registro_personal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personal.xsd" fecha="2013-10-20">
    
    <datos_generales>
        <empresa>Navarra 4 Internet</empresa>
        <trabajadores>6</trabajadores>
        <multinacional>NO</multinacional>
        <moneda>Euro</moneda>
        <sector>Tecnología</sector>
    </datos_generales>

    <departamentos>
        
        <departamento codigo="ADMIN">
            <nombre_dept>Administración</nombre_dept>
            
            <empleado>
                <nombre>Ana Sanz Ruiz</nombre>
                <rol>Jefe</rol>
                <baja>NO</baja>
                <salario>4700.58</salario>
                <usuario>anasan</usuario>
                <clave>3%abZKi6</clave>
            </empleado>
            
            <empleado>
                <nombre>Juan Gil Rus</nombre>
                <rol>Empleado</rol>
                <baja>SI</baja>
                <salario>2200.58</salario>
            </empleado>
            
            <empleado>
                <nombre>Lucas López Tapia</nombre>
                <rol>Empleado</rol>
                <baja>NO</baja>
                <salario>2215.65</salario>
            </empleado>
        </departamento>

        <departamento codigo="INFOR">
            <nombre_dept>Informática</nombre_dept>
            
            <empleado>
                <nombre>Isabel Gómez Pérez</nombre>
                <rol>Jefe</rol>
                <baja>SI</baja>
                <salario>5200.77</salario>
                <usuario>isabelgo</usuario>
                <clave>8$abcdHj</clave>
            </empleado>
            
            <empleado>
                <nombre>Oscar Lee Blesa</nombre>
                <rol>Empleado</rol>
                <baja>NO</baja>
                <salario>3109.26</salario>
            </empleado>
        </departamento>

        <departamento codigo="MARKE">
            <nombre_dept>Marketing</nombre_dept>
            
            <empleado>
                <nombre>Luis Mar Herreros</nombre>
                <rol>Jefe</rol>
                <baja>NO</baja>
                <salario>5111.09</salario>
                <usuario>invitado</usuario>
                <clave>2$xlzY#@</clave>
            </empleado>
        </departamento>

    </departamentos>
</registro_personal>
