=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Simulacro Examen/Factura1/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="datos_empresa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="cif" type="xs:string"/>
                            <xs:element name="telefono" type="xs:string"/>
                            <xs:element name="fax" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="datos_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:date"/>
                            <xs:element name="pedido" type="xs:integer"/>
                            <xs:element name="forma_pago" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="datos_cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="poblacion" type="xs:string"/>
                            <xs:element name="cod_postal" type="xs:integer"/>
                            <xs:element name="provincia" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="n_cliente" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="detalle_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="linea" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ref" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="cantidad" type="xs:integer"/>
                                        <xs:element name="precio" type="xs:decimal"/>
                                        <xs:element name="igv" type="xs:decimal"/>
                                        <xs:element name="importe" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="totales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="base_imponible" type="xs:decimal"/>
                            <xs:element name="porcentaje_igv" type="xs:decimal"/>
                            <xs:element name="cuota_igv" type="xs:decimal"/>
                            <xs:element name="total_factura" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
            <xs:attribute name="n_factura" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Simulacro Examen/Factura1/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="factura.xsl"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura.xsd" n_factura="999">
    
    <datos_empresa>
        <nombre>Equipos Digitales S.L.</nombre>
        <direccion>Av. Valladolid, Madrid 28015</direccion>
        <cif>Q-9876543</cif>
        <telefono>91.777.66.88</telefono>
        <fax>91.777.66.99</fax>
    </datos_empresa>

    <datos_factura>
        <fecha>2005-01-12</fecha>
        <pedido>731</pedido>
        <forma_pago>EFECTIVO</forma_pago>
    </datos_factura>

    <datos_cliente n_cliente="879">
        <nombre>Darío Bueno Gutiérrez</nombre>
        <direccion>Av. Oporto nº7 4ºd</direccion>
        <poblacion>Madrid</poblacion>
        <cod_postal>28043</cod_postal>
        <provincia>Madrid</provincia>
    </datos_cliente>

    <detalle_factura>
        <linea>
            <ref>MII93000F/8</ref>
            <descripcion>MICRO PENTIUM IV 3000MHZ FB800</descripcion>
            <cantidad>1</cantidad>
            <precio>230</precio>
            <igv>16.0</igv>
            <importe>266.80</importe>
        </linea>
        <linea>
            <ref>MB8QDIP4</ref>
            <descripcion>PLACA BASE QDI P4</descripcion>
            <cantidad>1</cantidad>
            <precio>180</precio>
            <igv>16.0</igv>
            <importe>208.80</importe>
        </linea>
        <linea>
            <ref>MEDD512M32</ref>
            <descripcion>DIMM DDR 512MB 3200</descripcion>
            <cantidad>2</cantidad>
            <precio>40</precio>
            <igv>16.0</igv>
            <importe>92.80</importe>
        </linea>
        <linea>
            <ref>HD250GSA7</ref>
            <descripcion>DISCO DURO 250GB S-ATA 7200</descripcion>
            <cantidad>4</cantidad>
            <precio>120</precio>
            <igv>16.0</igv>
            <importe>556.80</importe>
        </linea>
    </detalle_factura>

    <totales>
        <base_imponible>970.00</base_imponible>
        <porcentaje_igv>16.0</porcentaje_igv>
        <cuota_igv>155.20</cuota_igv>
        <total_factura>1125.20</total_factura>
    </totales>

</factura>
