=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/XSD - XML Schema Definition/esquema_factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datos_empresa" type="DefinicionEmpresa"/>
                <xs:element name="datos_factura" type="DefinicionDatosFactura"/>
                <xs:element name="datos_cliente" type="DefinicionCliente"/>
                <xs:element name="lineas_factura" type="DefinicionListaArticulos"/>
                <xs:element name="totales" type="DefinicionTotales"/>
            </xs:sequence>
            <xs:attribute name="numero" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DefinicionEmpresa">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="direccion" type="xs:string"/>
            <xs:element name="cif" type="xs:string"/>
            <xs:element name="telefono" type="xs:string"/>
            <xs:element name="fax" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DefinicionDatosFactura">
        <xs:sequence>
            <xs:element name="fecha" type="xs:date"/>
            <xs:element name="pedido_ref" type="xs:string"/>
            <xs:element name="forma_pago">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="EFECTIVO"/>
                        <xs:enumeration value="TARJETA"/>
                        <xs:enumeration value="TRANSFERENCIA"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DefinicionCliente">
        <xs:sequence>
            <xs:element name="n_cliente" type="xs:integer"/>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="direccion_envio" type="xs:string"/>
            <xs:element name="poblacion" type="xs:string"/>
            <xs:element name="cod_postal" type="xs:string"/>
            <xs:element name="provincia" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DefinicionListaArticulos">
        <xs:sequence>
            <xs:element name="linea" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ref" type="xs:string"/>
                        <xs:element name="descripcion" type="xs:string"/>
                        <xs:element name="cantidad" type="xs:integer"/>
                        <xs:element name="precio" type="FormatoMonedaEstricto"/>
                        <xs:element name="igv" type="xs:decimal"/>
                        <xs:element name="importe" type="FormatoMonedaEstricto"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DefinicionTotales">
        <xs:sequence>
            <xs:element name="base_imponible" type="FormatoMonedaEstricto"/>
            <xs:element name="porcentaje_igv" type="xs:decimal"/>
            <xs:element name="cuota_igv" type="FormatoMonedaEstricto"/>
            <xs:element name="total_factura">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="FormatoMonedaEstricto">
                            <xs:attribute name="moneda" type="xs:string" fixed="eur"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="FormatoMonedaEstricto">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/XSD - XML Schema Definition/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema_factura.xsd" numero="999">

    <datos_empresa>
        <nombre>Equipos Digitales S.L.</nombre>
        <direccion>Av. Valladolid, Madrid 28015</direccion>
        <cif>Q-9876543</cif>
        <telefono>91.777.66.88</telefono>
        <fax>91.777.66.99</fax>
    </datos_empresa>

    <datos_factura>
        <fecha>2005-01-12</fecha>
        <pedido_ref>731</pedido_ref>
        <forma_pago>EFECTIVO</forma_pago>
    </datos_factura>

    <datos_cliente>
        <n_cliente>879</n_cliente>
        <nombre>Darío Bueno Gutiérrez</nombre>
        <direccion_envio>Av. Oporto nº7 4ºd</direccion_envio>
        <poblacion>Madrid</poblacion>
        <cod_postal>28043</cod_postal>
        <provincia>Madrid</provincia>
    </datos_cliente>

    <lineas_factura>
        <linea>
            <ref>MII93000F/8</ref>
            <descripcion>MICRO PENTIUM IV 3000MHZ FB800</descripcion>
            <cantidad>1</cantidad>
            <precio>230.00</precio>
            <igv>16.0</igv>
            <importe>266.80</importe>
        </linea>
        <linea>
            <ref>MB8QDIP4</ref>
            <descripcion>PLACA BASE QDI P4</descripcion>
            <cantidad>1</cantidad>
            <precio>180.00</precio>
            <igv>16.0</igv>
            <importe>208.80</importe>
        </linea>
        <linea>
            <ref>MEDD512M32</ref>
            <descripcion>DIMM DDR 512MB 3200</descripcion>
            <cantidad>2</cantidad>
            <precio>40.00</precio>
            <igv>16.0</igv>
            <importe>92.80</importe>
        </linea>
         <linea>
            <ref>HD250GSA7</ref>
            <descripcion>DISCO DURO 250GB S-ATA 7200</descripcion>
            <cantidad>4</cantidad>
            <precio>120.00</precio>
            <igv>16.0</igv>
            <importe>556.80</importe>
        </linea>
    </lineas_factura>

    <totales>
        <base_imponible>970.00</base_imponible>
        <porcentaje_igv>16.0</porcentaje_igv>
        <cuota_igv>155.20</cuota_igv>
        <total_factura moneda="eur">1125.20</total_factura>
    </totales>

</factura>
