=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio XSD Caso Final 03 - Pedidos/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:choice>
                                <xs:element name="empresa">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[0-9]{4}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                
                                <xs:element name="cliente">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="mote" type="xs:string"/>
                                        </xs:sequence>
                                        <xs:attribute name="NIF" type="xs:ID" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>

                            <xs:element name="productos_solicitados">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="producto" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="fecha" type="xs:date"/>

                            <xs:element name="factura" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="emisor" type="xs:string"/>
                                        <xs:element name="total" type="xs:decimal" maxOccurs="unbounded"/>
                                        <xs:element name="fecha_fact" type="xs:date"/>
                                    </xs:sequence>
                                    <xs:attribute name="numfactura" type="xs:ID" use="required"/>
                                    <xs:attribute name="cliente_factura" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio XSD Caso Final 03 - Pedidos/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd">
    
    <pedido>
        <empresa>1234</empresa>
        
        <productos_solicitados>
            <producto>Ordenador Portátil</producto>
            <producto>Ratón inalámbrico</producto>
        </productos_solicitados>
        
        <fecha>2024-02-01</fecha>
        
        <factura numfactura="FAC-001" cliente_factura="C-1234">
            <emisor>PC Componentes S.L.</emisor>
            <total>850.50</total>
            <fecha_fact>2024-02-01</fecha_fact>
        </factura>
    </pedido>

    <pedido>
        <cliente NIF="N12345678">
            <mote>Pepe</mote>
        </cliente>
        
        <productos_solicitados>
            <producto>Monitor 24 pulgadas</producto>
        </productos_solicitados>
        
        <fecha>2024-02-05</fecha>
        
        </pedido>

</pedidos>
