=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 2 DTD - XML/reglas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listaventas (venta+)>

<!ELEMENT venta (importe, comprador, vendedor, fecha?, codigo_factura)>

<!ELEMENT importe (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT vendedor (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT codigo_factura (#PCDATA)>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 2 DTD - XML/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas SYSTEM "reglas.dtd">

<listaventas>
    <venta>
        <importe>150.50</importe>
        <comprador>Empresa A S.L.</comprador>
        <vendedor>Juan Pérez</vendedor>
        <fecha>2023-10-25</fecha>
        <codigo_factura>FAC-2023-001</codigo_factura>
    </venta>

    <venta>
        <importe>45.00</importe>
        <comprador>Cliente Particular</comprador>
        <vendedor>Ana Gómez</vendedor>
        <codigo_factura>FAC-2023-002</codigo_factura>
    </venta>
</listaventas>
