=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 1 DTD - XML/reglas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT productos (raton | teclado)*>

<!ELEMENT raton (codigo, descripcion?)>

<!ELEMENT teclado (codigo, descripcion, peso?)>

<!ELEMENT codigo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 1 DTD - XML/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos SYSTEM "reglas.dtd">

<productos>
    <raton>
        <codigo>M-LOG-01</codigo>
        <descripcion>Ratón ergonómico vertical</descripcion>
    </raton>

    <teclado>
        <codigo>K-COR-99</codigo>
        <descripcion>Teclado Mecánico K70</descripcion>
    </teclado>

    <raton>
        <codigo>M-GEN-02</codigo>
    </raton>

    <teclado>
        <codigo>K-LOG-MX</codigo>
        <descripcion>Teclado inalámbrico mini</descripcion>
        <peso>500g</peso>
    </teclado>
</productos>
