=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio XSD Caso Final 01 - Temperatura/temperatura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="registro_temperaturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="provincia" type="xs:string"/>
                
                <xs:element name="fecha_registro" type="xs:date"/>
                
                <xs:element name="temperatura_minima" type="TipoTemperatura"/>
                
                <xs:element name="temperatura_maxima" type="TipoTemperatura"/>
                
                <xs:element name="incidencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="incidencia" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="TipoNombreIncidencia"/>
                                        <xs:element name="severidad" type="TipoSeveridad"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="TipoTemperatura">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="-50"/>
            <xs:maxInclusive value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoNombreIncidencia">
        <xs:restriction base="xs:string">
            <xs:enumeration value="frío"/>
            <xs:enumeration value="nieve"/>
            <xs:enumeration value="lluvia"/>
            <xs:enumeration value="calor"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoSeveridad">
        <xs:restriction base="xs:string">
            <xs:enumeration value="alta"/>
            <xs:enumeration value="media"/>
            <xs:enumeration value="baja"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio XSD Caso Final 01 - Temperatura/temperatura.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro_temperaturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="temperatura.xsd">    
    <provincia>Teruel</provincia>
    <fecha_registro>2024-01-15</fecha_registro>
    
    <temperatura_minima>-12</temperatura_minima>
    <temperatura_maxima>8</temperatura_maxima>
    
    <incidencias>
        <incidencia>
            <nombre>frío</nombre>
            <severidad>alta</severidad>
        </incidencia>
        
        <incidencia>
            <nombre>nieve</nombre>
            <severidad>media</severidad>
        </incidencia>
    </incidencias>

</registro_temperaturas>
