=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 3 DTD - XML/reglas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listapedidos (pedido*)>

<!ELEMENT pedido (numero_serie, cantidad, peso?)>

<!ELEMENT numero_serie (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 3 DTD - XML/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listapedidos SYSTEM "reglas.dtd">

<listapedidos>
    <pedido>
        <numero_serie>SN-998877</numero_serie>
        <cantidad>50</cantidad>
        <peso>10kg</peso>
    </pedido>

    <pedido>
        <numero_serie>SN-112233</numero_serie>
        <cantidad>120</cantidad>
    </pedido>
</listapedidos>
