=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 6 XSD - XML/pedido.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" type="xs:string"/>
                <xs:element name="direccion" type="xs:string"/>
                
                <xs:element name="items">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="precio" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="numero" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== joseantoniopastorrivera-creator/Lenguaje-De-Marcas/Ecosistema-XML-XSD-XSLT/Ejercicio 6 XSD - XML/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedido.xsd">
    <cliente>Gabriela Romero</cliente>
    <direccion>C/Area del Triunfo, Granada</direccion>
    <items>
        <item numero="4">
            <nombre>Hamburguesa de bacon y queso</nombre>
            <precio>28</precio>
        </item>
        <item numero="3">
            <nombre>Refresco de naranja sin azúcar</nombre>
            <precio>9</precio>
        </item>
    </items>
</pedido>
